### ISSUE TITLE
Create UI 

### ISSUE THREAD

**Issue by aznjp** [aznjp/park-travel-app#1]
*Create a skeleton model for site structure (HTML) 

*Create sections 

  1. Weather Section
     * Current and 5-day forecast

  2.  Local Events 
     * (Relative and/or TBD)

  3. Lodging
     * Airbnb, hotels, etc...

**Comment by fondofhats** [comment]
Created Skeleton HTML5
 ### Libraries
  * Buluma
  * Font Awesome
  * Google Fonts
  * jQuery
  * Moment.js

**Comment by fondofhats** [comment]
Updated master and develop branches with skeleton UI
